[colors.normal]
black = "#1e1e2e"
red = "#1e1e2e"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#1e1e2e"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#858caa"

# background = "#1e1e2e"

# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
