swipe:
  3:
    left:
      command: 'xdotool key Shift+Super+d'
    right:
      command: 'xdotool key Shift+Super+a'
    up:
      command: 'xdotool key Super+a'
    down:
      command: 'xdotool key Ctrsl+Super+d'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+minus'
    out:
      command: 'xdotool key ctrl+plus'
