Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - clang-analyzer-*
      - google-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
      - cppcoreguidelines-*
      - cppcoreguidelines-avoid-non-const-global-variables
      - hicpp-*
      - misc-
      - performance-*
    Remove:
      - modernize-use-trailing-return-type
      - readability-magic-numbers
